[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "espvoice"
authors = [{name = "The ESPVoice Team", email = ""}]
dynamic = ["version", "description"]
